/**
 * Generates verified mate-in-one puzzles by playing random games with chess.js
 * and keeping positions where exactly one legal move delivers checkmate.
 * Output: src/data/puzzles.ts
 */
import { Chess } from 'chess.js';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const MAX_GAMES = 4000;
const TARGET = 16;

const puzzles = [];
const seen = new Set();

function countPieces(fen) {
  return fen.split(' ')[0].replace(/[^a-zA-Z]/g, '').length;
}

outer: for (let g = 0; g < MAX_GAMES && puzzles.length < TARGET; g++) {
  const game = new Chess();
  for (let ply = 0; ply < 120; ply++) {
    const moves = game.moves({ verbose: true });
    if (moves.length === 0) break;
    const move = moves[Math.floor(Math.random() * moves.length)];
    game.move(move);

    // check every legal follow-up for a mate-in-one
    if (countPieces(game.fen()) >= 8) {
      const nextMoves = game.moves({ verbose: true });
      const mates = [];
      for (const m of nextMoves) {
        game.move(m);
        if (game.isCheckmate()) mates.push(m);
        game.undo();
      }
      if (mates.length === 1) {
        const fen = game.fen();
        const key = fen.split(' ').slice(0, 2).join(' ');
        if (!seen.has(key)) {
          seen.add(key);
          puzzles.push({
            id: `pz-${puzzles.length + 1}`,
            fen,
            solution: mates[0].san,
            sideToMove: game.turn(),
            // order by piece count as a rough difficulty signal
            pieces: countPieces(fen),
          });
          if (puzzles.length >= TARGET) break outer;
        }
      }
    }
  }
}

puzzles.sort((a, b) => a.pieces - b.pieces);

const body = `import type { PuzzleRecord } from '../lib/types';

/**
 * Generated by scripts/gen-puzzles.mjs — every solution is a verified
 * mate-in-one found by replaying random games with chess.js.
 */
export const PUZZLES: PuzzleRecord[] = ${JSON.stringify(
  puzzles.map(({ id, fen, solution, sideToMove, pieces }) => ({
    id,
    fen,
    solution,
    sideToMove,
    mate: true,
    materialWin: 0,
    difficulty: pieces,
  })),
  null,
  2).replace(/"([a-zA-Z]+)":/g, '$1: ')};
`;

writeFileSync(join(__dirname, '..', 'src', 'data', 'puzzles.ts'), body);
console.log(`wrote ${puzzles.length} puzzles`);
