import type { PuzzleRecord } from '../lib/types';

/**
 * Generated by scripts/gen-puzzles.mjs — every solution is a verified
 * mate-in-one found by replaying random games with chess.js.
 */
export const PUZZLES: PuzzleRecord[] = [
  {
    id:  "pz-1",
    fen:  "1n1k2n1/3p4/5p2/2B3p1/1Q6/2N1PN2/2K5/2R5 w - - 3 40",
    solution:  "Qxb8#",
    sideToMove:  "w",
    mate:  true,
    materialWin:  0,
    difficulty:  13
  },
  {
    id:  "pz-5",
    fen:  "4k1n1/2Q2r2/2R1p3/4Pp1p/1B1PpP2/p4bPR/P7/4K3 w - - 1 52",
    solution:  "Qc8#",
    sideToMove:  "w",
    mate:  true,
    materialWin:  0,
    difficulty:  19
  },
  {
    id:  "pz-6",
    fen:  "4k1n1/2Q2r2/2R1p3/2B1Pp1p/3PpP2/p4bPR/P4K2/8 w - - 5 54",
    solution:  "Qc8#",
    sideToMove:  "w",
    mate:  true,
    materialWin:  0,
    difficulty:  19
  },
  {
    id:  "pz-11",
    fen:  "1Bk2b1r/1p2p1p1/r3N2p/n7/6b1/5P2/2PR3P/bN1K1B1R w - - 0 30",
    solution:  "Rd8#",
    sideToMove:  "w",
    mate:  true,
    materialWin:  0,
    difficulty:  21
  },
  {
    id:  "pz-8",
    fen:  "1Bk2b1r/1p2pNp1/r6p/3R3b/p1n3P1/2N2P2/2P4P/4KB1R w - - 1 25",
    solution:  "Rd8#",
    sideToMove:  "w",
    mate:  true,
    materialWin:  0,
    difficulty:  22
  },
  {
    id:  "pz-9",
    fen:  "1Bk2b1r/1p2pNp1/r6p/7b/2n3P1/p1N2P2/2PR3P/4KB1R w - - 0 26",
    solution:  "Rd8#",
    sideToMove:  "w",
    mate:  true,
    materialWin:  0,
    difficulty:  22
  },
  {
    id:  "pz-10",
    fen:  "1Bk2b1r/1p2pNp1/r6p/n6b/6P1/p4P2/2PR3P/1N2KB1R w - - 2 27",
    solution:  "Rd8#",
    sideToMove:  "w",
    mate:  true,
    materialWin:  0,
    difficulty:  22
  },
  {
    id:  "pz-7",
    fen:  "3rk3/pb3N1r/2p2np1/1B1Pp2p/P1PP1B1P/5KQ1/5Pn1/4q3 b - - 1 45",
    solution:  "Qe4#",
    sideToMove:  "b",
    mate:  true,
    materialWin:  0,
    difficulty:  23
  },
  {
    id:  "pz-12",
    fen:  "5r2/3NPk1p/1pp3pB/1b3B1n/Pn1P1P2/Np5R/3Q2P1/R3K3 w - - 1 40",
    solution:  "exf8=Q#",
    sideToMove:  "w",
    mate:  true,
    materialWin:  0,
    difficulty:  23
  },
  {
    id:  "pz-13",
    fen:  "5r2/3NPk1p/1pp3pB/1b3B1n/Pn1P1P2/N5R1/1p1Q2P1/R3K3 w - - 0 41",
    solution:  "exf8=Q#",
    sideToMove:  "w",
    mate:  true,
    materialWin:  0,
    difficulty:  23
  },
  {
    id:  "pz-14",
    fen:  "4r3/3NPk1p/1pp3pB/1b3B1n/P2P1P2/N2nQ1R1/1p4P1/R4K2 w - - 4 43",
    solution:  "Qe6#",
    sideToMove:  "w",
    mate:  true,
    materialWin:  0,
    difficulty:  23
  },
  {
    id:  "pz-15",
    fen:  "4r3/3NPk1p/1pp3pB/1b3B1n/P2P1P2/N2n2R1/4Q1P1/Rn3K2 w - - 0 44",
    solution:  "Qe6#",
    sideToMove:  "w",
    mate:  true,
    materialWin:  0,
    difficulty:  23
  },
  {
    id:  "pz-16",
    fen:  "5r2/3NPk1p/1pp3pB/1b1P1B1n/P4P2/n2n1QR1/2N3P1/R4K2 w - - 3 47",
    solution:  "exf8=Q#",
    sideToMove:  "w",
    mate:  true,
    materialWin:  0,
    difficulty:  23
  },
  {
    id:  "pz-3",
    fen:  "2bk1bnr/1Q1pp3/B6p/2N1Ppp1/3P1P2/p1Bq2PK/P6P/R4R2 w - - 1 34",
    solution:  "Qxc8#",
    sideToMove:  "w",
    mate:  true,
    materialWin:  0,
    difficulty:  25
  },
  {
    id:  "pz-4",
    fen:  "2bk1bnr/1Q2p3/B6p/2NpPpp1/1B1P1P2/p2q2PK/P6P/R4R2 w - d6 0 35",
    solution:  "Qxc8#",
    sideToMove:  "w",
    mate:  true,
    materialWin:  0,
    difficulty:  25
  },
  {
    id:  "pz-2",
    fen:  "2b1kbnr/1Q1pp3/n6p/2N1Ppp1/2BP1P2/p1B3PK/P3q2P/R5R1 w - - 1 32",
    solution:  "Qxc8#",
    sideToMove:  "w",
    mate:  true,
    materialWin:  0,
    difficulty:  26
  }
];
